pipeline {
    agent any

    environment {
        SONAR_PROJECT_KEY = 'my-next-app'
        SONAR_HOST_URL = 'http://sonarqube:9000'
        SONAR_LOGIN = credentials('sonar-token') // Ajouté via Jenkins > Credentials
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/lucas-BLV/manage-qualite.git'
            }
        }

        stage('Install') {
            steps {
                sh 'cd my-next-app && npm ci'
            }
        }

        stage('Lint') {
            steps {
                sh 'cd my-next-app && npx eslint .'
            }
        }

        stage('Build') {
            steps {
                sh 'cd my-next-app && npm run build'
            }
        }

        stage('Test') {
            steps {
                sh 'cd my-next-app && npm test || true'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh 'cd my-next-app && sonar-scanner'
                }
            }
        }
    }
}
